# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NewBaoAdmin_Activity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NewBaoAdmin_Common_pb2 as NewBaoAdmin__Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NewBaoAdmin_Activity.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('Z\007.;proto'),
  serialized_pb=_b('\n\x1aNewBaoAdmin_Activity.proto\x12\x05proto\x1a\x18NewBaoAdmin_Common.proto\"W\n TSAdminDoubleSeventhScoreRequest\x12\x10\n\x08phoneNum\x18\x01 \x01(\t\x12\x0f\n\x07pageNum\x18\x02 \x01(\x05\x12\x10\n\x08pageSize\x18\x03 \x01(\x05\"\xe2\x01\n!TSAdminDoubleSeventhScoreResponse\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\x05\x12\x10\n\x08phoneNum\x18\x04 \x01(\t\x12\x10\n\x08nickname\x18\x05 \x01(\t\x12\x14\n\x0c\x63urrentScore\x18\x06 \x01(\x05\x12=\n\x0fscoreRecordList\x18\x07 \x03(\x0b\x32$.proto.AdminDoubleSeventhScoreRecord\x12\x12\n\ntotalCount\x18\x08 \x01(\x05\"G\n#TSAdminDoubleSeventhScoreAddRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x13\n\x0bupdateScore\x18\x02 \x01(\x05\"K\n$TSAdminDoubleSeventhScoreAddResponse\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB\tZ\x07.;protob\x06proto3')
  ,
  dependencies=[NewBaoAdmin__Common__pb2.DESCRIPTOR,])




_TSADMINDOUBLESEVENTHSCOREREQUEST = _descriptor.Descriptor(
  name='TSAdminDoubleSeventhScoreRequest',
  full_name='proto.TSAdminDoubleSeventhScoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phoneNum', full_name='proto.TSAdminDoubleSeventhScoreRequest.phoneNum', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageNum', full_name='proto.TSAdminDoubleSeventhScoreRequest.pageNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='proto.TSAdminDoubleSeventhScoreRequest.pageSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=150,
)


_TSADMINDOUBLESEVENTHSCORERESPONSE = _descriptor.Descriptor(
  name='TSAdminDoubleSeventhScoreResponse',
  full_name='proto.TSAdminDoubleSeventhScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='proto.TSAdminDoubleSeventhScoreResponse.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorMsg', full_name='proto.TSAdminDoubleSeventhScoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='proto.TSAdminDoubleSeventhScoreResponse.uid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phoneNum', full_name='proto.TSAdminDoubleSeventhScoreResponse.phoneNum', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='proto.TSAdminDoubleSeventhScoreResponse.nickname', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentScore', full_name='proto.TSAdminDoubleSeventhScoreResponse.currentScore', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scoreRecordList', full_name='proto.TSAdminDoubleSeventhScoreResponse.scoreRecordList', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalCount', full_name='proto.TSAdminDoubleSeventhScoreResponse.totalCount', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=379,
)


_TSADMINDOUBLESEVENTHSCOREADDREQUEST = _descriptor.Descriptor(
  name='TSAdminDoubleSeventhScoreAddRequest',
  full_name='proto.TSAdminDoubleSeventhScoreAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='proto.TSAdminDoubleSeventhScoreAddRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateScore', full_name='proto.TSAdminDoubleSeventhScoreAddRequest.updateScore', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=452,
)


_TSADMINDOUBLESEVENTHSCOREADDRESPONSE = _descriptor.Descriptor(
  name='TSAdminDoubleSeventhScoreAddResponse',
  full_name='proto.TSAdminDoubleSeventhScoreAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='proto.TSAdminDoubleSeventhScoreAddResponse.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorMsg', full_name='proto.TSAdminDoubleSeventhScoreAddResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=529,
)

_TSADMINDOUBLESEVENTHSCORERESPONSE.fields_by_name['scoreRecordList'].message_type = NewBaoAdmin__Common__pb2._ADMINDOUBLESEVENTHSCORERECORD
DESCRIPTOR.message_types_by_name['TSAdminDoubleSeventhScoreRequest'] = _TSADMINDOUBLESEVENTHSCOREREQUEST
DESCRIPTOR.message_types_by_name['TSAdminDoubleSeventhScoreResponse'] = _TSADMINDOUBLESEVENTHSCORERESPONSE
DESCRIPTOR.message_types_by_name['TSAdminDoubleSeventhScoreAddRequest'] = _TSADMINDOUBLESEVENTHSCOREADDREQUEST
DESCRIPTOR.message_types_by_name['TSAdminDoubleSeventhScoreAddResponse'] = _TSADMINDOUBLESEVENTHSCOREADDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TSAdminDoubleSeventhScoreRequest = _reflection.GeneratedProtocolMessageType('TSAdminDoubleSeventhScoreRequest', (_message.Message,), dict(
  DESCRIPTOR = _TSADMINDOUBLESEVENTHSCOREREQUEST,
  __module__ = 'NewBaoAdmin_Activity_pb2'
  # @@protoc_insertion_point(class_scope:proto.TSAdminDoubleSeventhScoreRequest)
  ))
_sym_db.RegisterMessage(TSAdminDoubleSeventhScoreRequest)

TSAdminDoubleSeventhScoreResponse = _reflection.GeneratedProtocolMessageType('TSAdminDoubleSeventhScoreResponse', (_message.Message,), dict(
  DESCRIPTOR = _TSADMINDOUBLESEVENTHSCORERESPONSE,
  __module__ = 'NewBaoAdmin_Activity_pb2'
  # @@protoc_insertion_point(class_scope:proto.TSAdminDoubleSeventhScoreResponse)
  ))
_sym_db.RegisterMessage(TSAdminDoubleSeventhScoreResponse)

TSAdminDoubleSeventhScoreAddRequest = _reflection.GeneratedProtocolMessageType('TSAdminDoubleSeventhScoreAddRequest', (_message.Message,), dict(
  DESCRIPTOR = _TSADMINDOUBLESEVENTHSCOREADDREQUEST,
  __module__ = 'NewBaoAdmin_Activity_pb2'
  # @@protoc_insertion_point(class_scope:proto.TSAdminDoubleSeventhScoreAddRequest)
  ))
_sym_db.RegisterMessage(TSAdminDoubleSeventhScoreAddRequest)

TSAdminDoubleSeventhScoreAddResponse = _reflection.GeneratedProtocolMessageType('TSAdminDoubleSeventhScoreAddResponse', (_message.Message,), dict(
  DESCRIPTOR = _TSADMINDOUBLESEVENTHSCOREADDRESPONSE,
  __module__ = 'NewBaoAdmin_Activity_pb2'
  # @@protoc_insertion_point(class_scope:proto.TSAdminDoubleSeventhScoreAddResponse)
  ))
_sym_db.RegisterMessage(TSAdminDoubleSeventhScoreAddResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
